### ISSUE TITLE
Ignition Gazebo sim moving past commanded pose

### ISSUE THREAD

**Issue by MarqRazz** [Kinovarobotics/ros2_kortex#139]
Running Gazebo and commanding the arm with MoveIt I have seen issues with the arm not moving to the commanded pose, moving past the goal or some joint's continuing to move forever.

System Setup: [c3pzero container](https://github.com/MarqRazz/c3pzero/blob/main/doc/installation.md#build-and-run-the-docker-container) running Humble and Gazebo Fortress

![6dof_gen3_overshoot2](https://github.com/PickNikRobotics/ros2_kortex/assets/25058794/cde2d80a-b360-411a-be05-619612d717b1)

![6dof_gen3_overshoot3](https://github.com/PickNikRobotics/ros2_kortex/assets/25058794/c4e183c9-23e9-4255-b9d2-1993f864e7c5)

Here are some pic's of the goal pose and the ghost robot is showing the final pose of the arm as reported from simulation.
![image](https://github.com/PickNikRobotics/ros2_kortex/assets/25058794/ba5a7cce-4d99-4fbb-a5b1-a1e6ff061eb7)

![6dof_gen3_overshoot](https://github.com/PickNikRobotics/ros2_kortex/assets/25058794/63c08276-0aca-4117-b5a4-afaea04fbaf8)

**Comment by abake48** [comment]
Was experiencing this as well in a host environment. 
One way I was easily able to replicate this consistently using MoveIt:

- Have Velocity and Acceleration scaled to 0.1 (the default)
- Set goal to "random valid"
- click "Plan and Execute"
- during the execution of the trajectory, click "Stop"
- Observe the arm continue to move while Rviz states that trajectory execution has "Stopped"

https://github.com/PickNikRobotics/ros2_kortex/assets/7244387/068c476b-b3f8-4324-aa29-8feabbd399bd

**Comment by abake48** [comment]
Leaving this note here for myself or who ever is motivated to tackle this. 

One suggestions for a possible workaround or solution is to increase[ the effort parameter of each of the joints](https://github.com/PickNikRobotics/ros2_kortex/blob/eb95d3f7e09a0ff982222b7acf52d13f0642e4dc/kortex_description/arms/gen3/7dof/urdf/gen3_macro.xacro#L110)

**Comment by aalmrad** [comment]
Hello,

Apologies for the late reply. We are recently trying to tackle the github issues on our repositories more actively. I tried to replicate the issue by moving the robot to various random valid goals using ROS2 humble and Gazebo fortress. The robot moves to the set Goals then stops. I tried to stop it multiple times before reaching any of the set goals and it was responding promptly. I am aware that many modifications have been applied to the repository since then so please let me know if you still face the issue on the up-to-date main branch and we can work towards a solution.

Best,
Abed

**Comment by MarqRazz** [comment]
I agree updates to gz ros2_control have likely fixed this issue. I'm closing it and will update if I still have issues.
