### ISSUE TITLE
Services in ros2_kortex

### ISSUE THREAD

**Issue by julien-audet** [Kinovarobotics/ros2_kortex#229]
Hello,

I've looked at both the ros_kortex and ros2_kortex repositories, and it seems like ros_kortex has more functionalities than ros2_kortex. I am interested in using ros2 in a project with a Kinova Gen3 arm, and I would need access to some services like "Reading and setting the gravity vector" from control_config for example.

Are there any plans to make these services available in ros2?

**Comment by martinleroux** [comment]
Hi @julien-audet,
We do plan to release more updates to the ROS2 driver in the coming year, including configuration endpoints. However at this time we cannot make a commitment on a specific timeline.

Since the driver is simply a wrapper around our API that is built from source, you would have the option of implementing the endpoints that are needed specifically for your project. For example, you can find the API call to set the gravity vector in the ControlConfig client: https://github.com/Kinovarobotics/ros_kortex/blob/noetic-devel/kortex_driver/protos/ControlConfig.proto#L23

**Comment by julien-audet** [comment]
Hello @martinleroux,

I understand, thanks for the quick reply! I'll look into the option of implementing the services that I need for my project.
