### ISSUE TITLE
Gen 3 Lite MoveIt Limp Gripper

### ISSUE THREAD

**Issue by htchr** [Kinovarobotics/ros2_kortex#245]
Hello,

I'm trying to control the gripper using the included MoveIt configuration for the gen3 lite robot arm.
However, it seems that only one side can be controlled, and the other side hangs limp (see screenshot). 
Therefore it cannot actually grip anything in simulation; the object always falls away.
Is there anything I can do to fix this issue? 
Also, is there anyway to control the marker from the arm and not the "finger"? 

Thank you,

![Screenshot from 2024-10-16 14-59-10](https://github.com/user-attachments/assets/2d021dd3-1dae-4bf5-a25f-d3bb9c979e55)

**Comment by ssapsu** [comment]
hi

i think the problem is it's because symmetric
one side is clockwise and the other size is anti clockwise

**Comment by ssapsu** [comment]
like mirror

**Comment by ssapsu** [comment]
I had kind of that problem in isaac sim too

**Comment by htchr** [comment]
Hello @ssapsu were you able to fix the issue? I'm using the default Gazebo and MoveIt configurations.

**Comment by ssapsu** [comment]
I think it's because of limitation of implement specific joint like in your case and my case which was robotiq 2f 85. 

Becasue it opens and closes symmetric with single motor but i'm afraid they implemented separately

In my case i filtered ros2 topic to only hear left side and i gave a command on the left side

Maybe you can change your gripper's config file so you can correct right

**Comment by aalmrad** [comment]
Hello @htchr ,

The issue has been recently fixed after merging the following [PR](https://github.com/Kinovarobotics/ros2_kortex/pull/252)
